-- MySQL Script generated by MySQL Workbench
-- Tue Apr 28 17:27:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cms-2020
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cms-2020
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cms-2020` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `cms-2020` ;

-- -----------------------------------------------------
-- Table `cms-2020`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms-2020`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms-2020`.`logAlteraSenha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms-2020`.`logAlteraSenha` (
  `idlogAlteraSenha` INT NOT NULL AUTO_INCREMENT,
  `dataHora` DATETIME NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idlogAlteraSenha`, `usuarios_idusuarios`),
  INDEX `fk_logAlteraSenha_usuarios_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_logAlteraSenha_usuarios`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `cms-2020`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
